backend:
  name: git-gateway
  branch: main
media_folder: "src/img/uploads"  
public_folder: "/img/uploads"
collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/gallery"
    create: true
    slug: "{{title}}"
    fields: 
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}



